[package]
name = "aoc2018"
version = "0.1.0"
authors = ["scturtle <scturtle@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "*"
itertools = "*"
dotenv = "*"
regex = "*"

[lib]
name = "common"
path = "src/lib.rs"

[[bin]]
name = "day20"
path = "src/day20.rs"
